# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    target-branch: "main"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-bot"
    commit-message:
      prefix: "(chore)"
    pull-request-branch-name:
      separator: "_"
    open-pull-requests-limit: 15
    groups:
      lint-dependencies:
        patterns:
          - "*eslint*"
      patternfly-dependencies:
        patterns:
          - "*patternfly*"
      test-dependencies:
        patterns:
          - "*jest*"
          - "*testing-library*"
      ci-dependencies:
        patterns:
          - "*" # update remaining deps in single PR
