# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: 'cost-management-ros'
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: 'cost-management-ros'
    spec:
      feoConfigEnabled: true
      bundleSegments:
        - segmentId: 'cost-management-staging'
          bundleId: 'staging'
          position: 100
          navItems:
            - id: 'cost-management-staging.nav'
              title: 'Cost Management'
              expandable: true
              routes:
                - id: 'cost-management-staging.ros'
                  title: 'ROS'
                  expandable: true

                  # Must match apps/koku-ui-ros/src/utils/paths.ts base
                  routes:
                    - id: 'cost-management-staging.ros.badge'
                      title: 'Optimizations badge'
                      href: '/staging/cost-management/ros/optimizations/badge'
                    - id: 'cost-management-staging.ros.link'
                      title: 'Optimizations link'
                      href: '/staging/cost-management/ros/optimizations/link'
                    - id: 'cost-management-staging.ros.summary'
                      title: 'Optimizations summary'
                      href: '/staging/cost-management/ros/optimizations/summary'
                    - id: 'cost-management-staging.ros.table'
                      title: 'Optimizations table'
                      href: '/staging/cost-management/ros/optimizations/table'
                    - id: 'cost-management-staging.ros.containers-table'
                      title: 'Optimizations containers table'
                      href: '/staging/cost-management/ros/optimizations/table/containers'
                    - id: 'cost-management-staging.ros.projects-table'
                      title: 'Optimizations projects table'
                      href: '/staging/cost-management/ros/optimizations/table/projects'
                    - id: 'cost-management-staging.ros.details'
                      title: 'Optimizations details'
                      href: '/staging/cost-management/ros/optimizations/details'
                    - id: 'cost-management-staging.ros.ocp-breakdown'
                      title: 'Optimizations OCP breakdown'
                      href: '/staging/cost-management/ros/optimizations/ocp/breakdown'
                    - id: 'cost-management-staging.ros.breakdown'
                      title: 'Optimizations breakdown'
                      href: '/staging/cost-management/ros/optimizations/breakdown'
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: 'Cost Management ROS UI'
      deploymentRepo: https://github.com/project-koku/koku-ui/apps/koku-ui-ros
      frontend:
        paths:
          - '/apps/cost-management-ros'
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: "/apps/cost-management-ros/fed-mods.json"
        modules:
          - id: 'cost-management-ros'
            module: './RootApp'
            routes:
              - pathname: '/staging/cost-management/ros'
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/cost-mgmt-dev-tenant/koku-ui-ros
