# Run this workflow for PRs only. Travis is required to push via insights-frontend-builder-common scripts

name: Pull request
on:
  pull_request:
    branches: [ main, master, prod-beta, prod-stable, stage-beta, stage-stable ]
env:
  BRANCH: ${{ github.base_ref }}

jobs:
  build:
    name: koku-ui build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set Node.js packages yarn cache directory
        id: yarn-cache-dir
        run: echo ::set-output name=CACHE_DIR::$(yarn cache dir)
      - name: Node.js yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn
      - name: Node.js modules cache
        uses: actions/cache@v2
        id: modules-cache
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-modules
      - name: Install Node.js packages
        if: ${{ steps.modules-cache.outputs.cache-hit != 'true' }}
        run: yarn --frozen-lockfile
      - name: Check manifest
        if: ${{ success() }}
        run: ${{ github.workspace }}/.travis/check_manifest.sh
      - name: Lint
        if: ${{ success() }}
        run: yarn lint
      - name: Test
        if: ${{ success() }}
        run: yarn test --coverage --maxWorkers=4
      - name: Build
        if: ${{ success() }}
        run: yarn build
      - name: Code coverage
        if: ${{ success() }}
        uses: codecov/codecov-action@v1
