# https://github.com/marketplace/actions/close-stale-issues

name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    name: Close stale issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-close: 14
          days-before-issue-stale: 30
          days-before-pr-close: 14
          days-before-pr-stale: 30
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          close-pr-message: "This PR was closed because it has been inactive for 14 days since being marked as stale."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity."
          stale-pr-message: "This PR is stale because it has been open for 30 days with no activity."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
